[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  SITE_URL = "https://www.devfokus.com"

# Headers for caching static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"